### PR TITLE
MACT-74: Align hidden password to the middle

### PR DESCRIPTION
**Pull request by guillegr123**

### CODE REVIEW

**Review by FerjoCode — APPROVED** [review]
Looks good to me!

As a note, I think ticket description say something about make the "show" button closer to the password value, but I don't know how mandatory this is.

**Comment by guillegr123** [comment]
Nice catch! I'll try to adjust that too.

**Comment by guillegr123** [comment]
@FerjoCode I moved the toggle button close to the password value, and I updated the mask characters to use the same ones as in the password inputs. This PR is ready for review again.

**Review by FerjoCode — APPROVED** [review]
lgtm!

**Pull request merged**
